export class Leads {
    plid:number;
    salutation:string;
    first_Name:string;
    middle_Name:string;
    last_Name:string;
    title:string;
    company:string
    industry:string;
    phone_Number:string;
    mobile_Number:string;
    email:string;
    lead_Status:number;
    owner:string;
    no_Of_Employees:string;
    lead_Source:string;
    address:string;
    pincode:string;
    country:string;
    state:string;
    city:string;
    rating:string;
    creationDate:Date;
}
